import { Injectable, HttpException, HttpStatus } from '@nestjs/common';

@Injectable()
export class KycService {
  // ML microservice base URL (Digital Ocean droplet). Configured via ML_BASE_URL env var.
  private readonly ML_BASE_URL =
    process.env.ML_BASE_URL ?? 'http://64.227.163.65';

  async submit(body: any) {
    try {
      console.log('--- STARTING KYC ML PIPELINE ---');
      console.log(`Processing Application: ${body.application_id}`);

      // 1. Extract the URLs from Jad's frontend payload structure
      const frontUrl = body.document_urls?.front_url;
      const backUrl = body.document_urls?.back_url;
      const faceFrames = body.biometric_urls?.face_frames;

      if (!frontUrl || !backUrl) {
        throw new Error('Missing front_url or back_url in payload.');
      }

      // ---------------------------------------------------------
      // STEP 1: ID EXTRACTION (Port 8000)
      // ---------------------------------------------------------
      console.log(`[1/2] Sending ID to ${this.ML_BASE_URL}:8000...`);
      const idResponse = await fetch(`${this.ML_BASE_URL}:8000/extract-id-data`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          front_url: frontUrl,
          back_url: backUrl
        })
      });

      if (!idResponse.ok) {
        const err = await idResponse.json().catch(() => ({ detail: idResponse.statusText }));
        throw new Error(`ID Extraction Failed: ${err.detail}`);
      }

      const idResult = await idResponse.json();
      console.log('[1/2] Success! Face cropped and data extracted.');

      // Grab the base64 YOLO cropped face generated by your Python code
      const croppedFaceB64 = idResult.data?.id_photo_base64;
      if (!croppedFaceB64) {
        throw new Error('ML could not detect/crop a face from the ID card.');
      }

      // ---------------------------------------------------------
      // STEP 2: FACE VERIFICATION (Port 8001)
      // ---------------------------------------------------------
      let faceHtmlReport = 'No live photos provided for verification.';
      
      if (faceFrames && faceFrames.length > 0) {
        console.log(`[2/2] Sending Biometrics to ${this.ML_BASE_URL}:8001...`);

        // Your Python code STRICTLY wants exactly 3 URLs to avoid crashing
        const top3Frames = faceFrames.slice(0, 3);

        const faceResponse = await fetch(`${this.ML_BASE_URL}:8001/visualize-pipeline`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            id_face_base64: croppedFaceB64,
            live_photo_urls: top3Frames
          })
        });

        if (!faceResponse.ok) {
           throw new Error(`Face Verification Failed: ${faceResponse.statusText}`);
        }

        // Port 8001 returns an HTML string visualization, not JSON!
        faceHtmlReport = await faceResponse.text();
        console.log('[2/2] Success! Biometric HTML report generated.');
      }

      console.log('--- KYC PIPELINE COMPLETE ---');

      // Return everything back to the frontend
      return {
        success: true,
        message: 'KYC ML Pipeline executed successfully',
        extractedIdData: idResult.data,
        faceVerificationHtml: faceHtmlReport, 
        status: 'Fingerprint Required'
      };

    } catch (error: any) {
      console.error('KYC Error:', error.message);
      // Throw a proper HTTP error so the frontend knows it failed
      throw new HttpException(
        { success: false, message: error.message },
        HttpStatus.BAD_REQUEST
      );
    }
  }

  // --- We leave Jad's other placeholders alone for now ---
  getStatus(userId: string) {
    return { success: true, message: 'KYC status endpoint', userId, status: 'Pending' };
  }

  resubmit(applicationId: string, body: any) {
    return { success: true, message: 'KYC resubmit endpoint', applicationId, status: 'Resubmission Received' };
  }
}